# Generated by Django 4.2 on 2023-12-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0003_profile_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rank',
            new_name='level',
        ),
    ]
