# Generated by Django 4.2.5 on 2023-12-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0004_rename_rank_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
