# Generated by Django 4.2.5 on 2023-12-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0008_alter_profile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(0, 'Пользователь'), (1, 'Активный пользователь'), (2, 'Эксперт'), (3, 'Лидер'), (4, 'Администрация⭐')], default=0),
        ),
    ]
