# Generated by Django 4.2 on 2023-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isDiscount',
            field=models.BooleanField(default=False),
        ),
    ]
